#!/bin/bash

# wait till there is a network connection
while true; do
    wget -q --tries=7 --timeout=20 --spider http://google.com
    if [[ $? -eq 0 ]]; then
        # Online
        break
    else
        # Offline
        sleep 2
    fi
done

UPD=$(check_updates)
REPOS=$(echo $UPD | awk '{print $1}')
AUR=$(echo $UPD | awk '{print $3}')

# fancy label
# FIRSTSEP="%{B$POLYBAR_BACKGROUND}%{F$POLYBAR_COLOR1_LIGHT}%{T2}%{T-}%{F-}%{B-}"
# FIRSTPART="%{B$POLYBAR_COLOR1_LIGHT}  %{B-}"
# MIDDLESEP="%{B$POLYBAR_COLOR1_LIGHT}%{F$POLYBAR_COLOR1}%{T2}%{T-}%{F-}%{B-}"
# MIDDLEPART="%{B$POLYBAR_COLOR1} $REPOS %{B-}"
# ENDSEP="%{B$POLYBAR_COLOR1}%{F$POLYBAR_COLOR1_DARK}%{T2}%{T-}%{F-}%{B-}"
# ENDPART="%{B$POLYBAR_COLOR1_DARK} $AUR %{B-}"
# VERYENDSEP="%{B$POLYBAR_COLOR1_DARK}%{F$POLYBAR_BACKGROUND}%{T2}%{T-}%{F-}%{B-}"

# echo $FIRSTSEP$FIRSTPART$MIDDLESEP$MIDDLEPART$ENDSEP$ENDPART$VERYENDSEP

# get the right color
color=$(cat ~/.config/polybar/poly_colors | grep "color1 " | awk '{print $NF}')


# regular label
echo "$REPOS  %{F$color}%{F-}  $AUR"
