#!/bin/bash

COLORS_FILE=~/.config/polybar/poly_colors
player_status=$(playerctl status 2> /dev/null)
# polyback=$(grep "background #" $COLORS_FILE | awk '{print $NF}')
# trans=#00000000
# polyfore=$(grep "foreground #" $COLORS_FILE | awk '{print $NF}')

# polyback=#0f0

# lbl="%{B$trans}%{F$polyback}%{T3}%{T-}%{F-}%{B-}"
# rbl="%{B$trans}%{F$polyback}%{T3}%{T-}%{F-}%{B-}"
# ltmp="%{B$polyback}%{F$polyfore}"
# rtmp="%{B-}%{F-}"
# lt="%{B$POLYBAR_ORSHADE4}%{F$POLYBAR_ORSHADE3}%{T5}%{T-}%{F-}%{B-}%{B$POLYBAR_ORSHADE4}%{F$POLYBAR_FONT_FORE} "
# rt=" %{B-}%{F-}%{B$POLYBAR_BACKGROUND}%{F$POLYBAR_ORSHADE4}%{T5}%{T-}%{F-}%{B-}"
lt=
rt=

if [ "$player_status" = "Playing" ]; then
    outstr="  $(playerctl metadata title) - $(playerctl metadata artist) "
elif [ "$player_status" = "Paused" ]; then
    outstr="  $(playerctl metadata title) - $(playerctl metadata artist) "
else
    outstr=" "
fi

echo "$lt`echo $outstr|cut -c1-50`$rt"
