#!/bin/bash

COLORS_FILE=~/.config/polybar/poly_colors
player_status=$(playerctl status 2> /dev/null)
# polyback=$(grep "background #" $COLORS_FILE | awk '{print $NF}')
# trans=#00000000
# polyfore=$(grep "foreground #" $COLORS_FILE | awk '{print $NF}')

# polyback=#0f0

# lbl="%{B$trans}%{F$polyback}%{T3}%{T-}%{F-}%{B-}"
# rbl="%{B$trans}%{F$polyback}%{T3}%{T-}%{F-}%{B-}"
# ltmp="%{B$polyback}%{F$polyfore}"
# rtmp="%{B-}%{F-}"
lbl=
rbl=
ltmp=
rtmp=

if [ "$player_status" = "Playing" ]; then
    echo " $(playerctl metadata title) - $(playerctl metadata artist)"
elif [ "$player_status" = "Paused" ]; then
    echo " $(playerctl metadata title) - $(playerctl metadata artist)"
else
    echo " "
fi
