#!/bin/bash

# This script is used to detect the current audio sink, so the appropriate icon
# can be selected for the volume module

# getting the colors
iconcolor=#0f0f0f
mutecolor=#0f0f0f

# the main script
blue=$(pacmd list-sinks | grep -e 'name:' -e 'index:' | grep -A2 \*)

if [[ $blue == *"bluez"* ]]
then
    icon=
    vol=" - "
else
    blue=$(pacmd list-sinks | grep active)
    if [[ $blue == *"headphone"* ]]
    then icon=
    else icon=墳
    fi
    mute=$(pamixer --get-mute)
    if [[ $mute == "false" ]]
    then vol="$(pamixer --get-volume)%"
    else vol="mute"
    fi

fi

echo "  %{F$iconcolor}$icon $vol%{F-}  "
