#!/bin/bash

# This script is used to detect the current audio sink, so the appropriate icon
# can be selected for the volume module
blue=$(pacmd list-sinks | grep -e 'name:' -e 'index:' | grep -A2 \*)

if [[ $blue == *"bluez"* ]]
then
    icon=
    vol=" - "
else
    blue=$(pacmd list-sinks | grep active)
    if [[ $blue == *"headphone"* ]]
    then 
        icon=
    else 
        icon=墳
    fi
    vol=" $(pamixer --get-volume)% "
fi


# FIRST_SEP="%{B$POLYBAR_BACKGROUND}%{F$POLYBAR_COLOR5}%{T2}%{T-}%{F-}%{B-}"
# FIRST="%{B$POLYBAR_COLOR5} $icon %{B-}"
# MIDDLESEP="%{B$POLYBAR_COLOR5}%{F$POLYBAR_COLOR5_DARK}%{T2}%{T-}%{F-}%{B-}"
# echo $FIRST_SEP$FIRST$MIDDLESEP

color=$(grep "color6 #" ~/.config/polybar/poly_colors | awk '{print $NF}')
ico=%{F$color}$icon%{F-}

echo $ico$vol
