#!/bin/bash

# This script is used to detect the current audio sink, so the appropriate icon
# can be selected for the volume module

# getting the colors
iconcolor=$(grep "color6 #" ~/.config/polybar/poly_colors | awk '{print $NF}')
mutecolor=$(grep "foreground-dark #" ~/.config/polybar/poly_colors | awk '{print $NF}')

# the main script
blue=$(pacmd list-sinks | grep -e 'name:' -e 'index:' | grep -A2 \*)

if [[ $blue == *"bluez"* ]]
then
    icon=
    vol=" - "
else
    blue=$(pacmd list-sinks | grep active)
    if [[ $blue == *"headphone"* ]]
    then icon=
    else icon=墳
    fi
    mute=$(pamixer --get-mute)
    if [[ $mute == "false" ]]
    then vol="$(pamixer --get-volume)%"
    else vol="%{F$mutecolor}mute%{F-}"
    fi

fi


# FIRST_SEP="%{B$POLYBAR_BACKGROUND}%{F$POLYBAR_COLOR5}%{T2}%{T-}%{F-}%{B-}"
# FIRST="%{B$POLYBAR_COLOR5} $icon %{B-}"
# MIDDLESEP="%{B$POLYBAR_COLOR5}%{F$POLYBAR_COLOR5_DARK}%{T2}%{T-}%{F-}%{B-}"
# echo $FIRST_SEP$FIRST$MIDDLESEP

echo "%{F$iconcolor}$icon%{F-} $vol"
